### ISSUE TITLE
Empty line after block end css

### ISSUE THREAD

**Issue by barbuslex** [victorporof/Sublime-HTMLPrettify#129]
Hi,

Is it possible to make empty line after block end in css ?

``` css
strong {
    color: #222;
}
abbr {...}
```

Like this : 

``` css
strong {
    color: #222;
}

abbr { ... }
```

Thanks
