### ISSUE TITLE
Less error when using pseudo class selectors

### ISSUE THREAD

**Issue by bertyhell** [victorporof/Sublime-HTMLPrettify#151]
the formatter make a mistake when using pseudo class selectors:

an example:

``` CSS
  tr {
    cursor: pointer;
    &:hover {
      background-color: #ddd;
    }
  }
```

gets formatted to this:

``` CSS
  tr {
    cursor: pointer;
    &: hover {
      background-color: #ddd;
    }
  }
```

notice the space before 'hover'
this isn't valid anymore.

((wrong syntax highlighting in the code examples cause less doesn't seem to work on github))
