### ISSUE TITLE
LESS/SCSS : Referencing Parent Selectors: &

### ISSUE THREAD

**Issue by vincentVDB** [victorporof/Sublime-HTMLPrettify#255]
In preference file I have :
"newline_between_rules": true, // Add a new line after every css rule

But in fact I haven't new line before all &-xxx  
```css
.col {
  height: 100%;
  display: inline-block;
  &-narrow {
    width: $seg-thickness;
  }
  &-wide {
    width: $seg-size - 2 * ($seg-thickness + 6px);
  }
}

.row {
  width: $seg-size;
  &-low {
    height: $seg-thickness;
  }
  &-high {
    height: $seg-thickness * 3;
  }
}

.seg {
  border: 1px solid $light;
  &-on {
    background-color: $site-color;
  }
}
}
```
