### ISSUE TITLE
How to disable new line after CSS Comment

### ISSUE THREAD

**Issue by shuvogm** [victorporof/Sublime-HTMLPrettify#274]
Is there a way to remove new line after CSS Comments using Sublime-HTMLPrettify ?

I have seen this: https://github.com/victorporof/Sublime-HTMLPrettify#using-your-own-jsbeautifyrc-options But could not find a solution.

**It Does:**
```css
/* FlexSlider Styles
*********************************/

.flexslider {
    margin: 0;
    padding: 0;
}
```

**I Want:**
```css
/* FlexSlider Styles
*********************************/
.flexslider {
    margin: 0;
    padding: 0;
}
```
