### ISSUE TITLE
SCSS pseudo class broken

### ISSUE THREAD

**Issue by rafalolszewskii** [victorporof/Sublime-HTMLPrettify#363]
I've run only into one issue which is broken pseudo selector.

Before prettifying
```scss
&:not(:first-of-type) {
    * {
        color: $labelColor;
    }
}
```

And after prettifying
```scss
&:not(: first-of-type) {
    * {
        color: $labelColor;
    }
}
```

Please note the space between `:` and `first-of-type`. Afterwards node is not able to compile SCSS with this kind of formatted code.
